

//@version = 3

study(title="Daily Range | Volatility in persental %%", shorttitle="Daily Range Volatility [© DevSergo [.com] aka kiti-kiti]")

amplitude = ((high - low)/((high+low)/2))*100
average30 = sma(amplitude, 30)
average3 = sma(amplitude, 3)
average3_5 = sma(average3, 3)

plot(amplitude, style=columns, color=silver)
plot(average30, color=blue)
plot(average3, color=red)
plot(average3_5, color=green)
